title: Stack Problems
description: My Personal Stack Problems
author: yulight    
github: https://github.com/yulight
about: I am freelance developer. Currently doing more in backend, actually in Python and Django.
urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/yulight
    - text: XML Feed
      url: /feed.xml
url: "https://yulight.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown